# file: postgresql/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: Ansibles
  description: "Install and configure PostgreSQL, dependencies, extensions, databases and users."
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - database
  - database:sql

dependencies: []
