version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - smtp

  guard:
    build:
      context: .
      dockerfile: dockerfiles/web
    volumes:
      - .:/app:cached
    links:
      - db
    command: bundle exec guard --no-interactions

  db:
    image: postgres:10.5
    ports:
      - "5432"

  smtp:
    build:
      context: .
      dockerfile: dockerfiles/smtp
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    ports:
      - "2525:2525"

  redis:
    image: redis:4.0

  worker:
    build:
      context: .
      dockerfile: dockerfiles/worker
    volumes:
      - .:/app:cached
      # This needs to share the directory containing email content between
      # smtp server and workers
      - ./tmp/emails:/tmp:cached
    links:
      - db
      - redis
      - postfix

  postfix:
    image: juanluisbaptiste/postfix
    environment:
      - SMTP_SERVER=mailcatcher
      - SMTP_PORT=1025
      # The username and password are actually ignore by mailcatcher but need
      # to be set to keep this container happy
      - SMTP_USERNAME=foo@bar.com
      - SMTP_PASSWORD=XXXXXXXX
      - SERVER_HOSTNAME=cuttlefish.io
    volumes:
      - ./postfix_log:/var/log:cached
    links:
      - mailcatcher

  mailcatcher:
    build:
      context: .
      dockerfile: dockerfiles/mailcatcher
    ports:
      - "1080:1080"

  log:
    build:
      context: .
      dockerfile: dockerfiles/log
    volumes:
      - .:/app:cached
      - ./postfix_log:/var/log:cached
    links:
      - db
