---
google_analytics_code: UA-3107958-16
secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38623131363436333165333937306663373131393564656134343530326534363664356661336330
          3161613761353563326462643764323966353564333665610a623238633038393930343332313161
          34313361643466353632336333326334653461663062356339656231326266376137656234396166
          6161346264613834350a376535383030303534636537353330636437356636616531363962626134
          33363161663564363835383165376630643835633838636465343065316134343338313562306562
          33656533323035636134353730313831396639626136363737623762636564653563313164643761
          63663936356163646531643061393561343565353338393961396236653965396633636339333363
          38626166346564383635656462643865656162303733333265376666343030333336316466623733
          31373164656630326333336564623834643665613938336261353466336166613239323539366234
          31356165613764383931613635356431386336386562653861343163346337383039666165656238
          666530393337653433343137376433646637
devise_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36373031323236653931316239666434633562623033336137353264353433306435356130373031
          6338336666636332613038356339313233646634323532610a343830626262346636643965613361
          34626261326333373033613130633939303663616532333736326436313830303135613163313762
          3565303031613631360a336630323233303466376131383438376335336462393133646531656434
          32323234313339643334373533653165616637313566323265366431336538653161336661376339
          32633262333334383361353365663336393134383837653466653635383565623961613461393262
          39373061326136306561376439373536383132646330613530643532383035653136653564643131
          36623835666662643531333662326363383162356565646430343466346665663138343161306366
          30653666303334653533396265653032383534323039373261623531313636383964303539306533
          65663761333836336566623138623933623332383430656236393763376637623263366561303234
          346162376134356466653231333333376365
new_relic_license_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62393735366133356434623166663366386432663433313836656665666232626665633332346465
          3837376236616437346536303735383730633438643931320a633666323936346132346435386362
          33636131393835326462623033303263346362626363383566343962343464366463386335653763
          6337653936343732340a653236336165323230343964303636656630306438666337626666663637
          30363130666632313237343565366230643131333537363430313934343435393936393032326536
          3134643564383863363665656264326135333538363039343037
new_relic_app_name: Cuttlefish
new_relic_agent_enabled: False
honeybadger_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66616133623039636430373561626361646263373462383538356333646237333133373930306637
          3365323230343966333436323666646234323164626139350a316430653961383732386164666566
          61373534636535356235343037373061663639303038313665623766646530306464333063303738
          3565656632356633630a333862626365316131353061316436333162383165383439663562323962
          6335
s3_bucket: cuttlefish-archives
aws_access_key_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386634316430616132373663666233653461353139663838396463376636396236336137383065
          3331346538306636313731353739616537363537336136380a346238373333353662346134383831
          63643734636664626536613264616438343133303935613837343835656638343834336133643735
          3637646463356530310a386461316433613238666462323138636164363530376634303136333139
          32663662666134373735303163383238626666353561313864663335353831313836
aws_secret_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34373632323237303365663764383362313738333934653432653063653938356132323061643435
          6139663239353461646538633963333736616238633733330a306465653563366232336530623738
          39393464313232626237646133373962653739303032646531343935663133353361373765363931
          3637646533326363360a353266366432323661386638653436323464323934313562313561383430
          37643734613863326636383631336531666665643232373066366466636536306664633663366137
          6136343033326464666363356338313833386431633936653139
encrypted_backup_aws_access_key:  !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37386264316364623062373738633838373434666564623666316432303639656433646635386264
          3630393333316238336461366663356230633535323364340a323236623863313966633566396537
          34376362633366653935303334306365393835636261646531643637353838343531646635386232
          3533616432313364310a663131326336373063643238636363653439363530326261333536633536
          62393631303263336632346564303038356634326663663766306230356331396434
encrypted_backup_secret_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39653133393665333832626437316239336331373439343963616165303762366237343164653939
          3763306664643232623366646139303938636562383532640a636637653230316565616333303665
          66353934363138646234613165373534346236613635633935623365313131363564613931613466
          6231626139303361630a333666653232303165663738303934353365323439666234313239623161
          61343064346130336136316137313261363661643932323537363833656530646565353132663632
          3261383935303366303232323262643237626338333232343962
encrypted_backup_passphrase: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39373936633661643133366131616434643864333733383030336262383933343730353134333861
          3738333361666535393166373839353635333735303265610a343736636339663833356533656131
          62616239613835376636363038376262653966633131393934666334383230396431336563663838
          3033663131306262370a613836323133616535333230633430326366336537616461383962646432
          35656439313431623034613331373032373964626435336635313362316139333161
cuttlefish_hash_salt: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62336633333166323233306233626562323336326462333436663764646165333562613032663230
          3436356132353437333738353332353339393761383033390a623735613832313036623434396663
          31303565396465353232623237373963363061663566396130316365636137393564366231656433
          3862353232306237320a386439333431633138313037346230393761323063623335363633333234
          3836
db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31316535323766366138363065336161383631306232363931383062356435356535373438666364
          3964383765396263333334336435396234613662373961610a656263626237666166393032616133
          37383032396637316531383166636666616164653665303535323936643362383765636334336462
          3437613838386432650a303961323965376162613834316631623662386531366133376231373935
          30633830323535363939393263626264306337663731653831323437343664616638
jwt_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39326163303137323565303266396337663138313039613538376131646263643639366465353737
          3863656130356464323565613732656138623935346265350a623832666265346566306461636130
          31353761373563633231643438366563663036643930643432373735626265623533363533623738
          3831646563633465640a616137323831613262366137613633336439636665613532336637333339
          39653239646632396430386465613264616436333434303562646462333930656465
# db_host, db_root_username and db_root_password are outputs of running terraform on oaf/infrastructure
db_host: lin-25965-9688-pgsql-primary-private.servers.linodedb.net
db_root_username: linpostgres
db_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33393336376438313530616562303533663066616337613266303364393661353238323232623333
          6664303031373936646263613064643133373764323763330a386632303037353163336534636135
          62373737343434313966623738646262356337313563663166636230343334356332366663363339
          3232313837336162310a343162353038613535636535353065343831636634346263323664393663
          66353730313535616664393765336430386439386364623664616631343439376363