# From https://github.com/antirez/redis-hashes
redis_checksums:
  2.8.0-rc5: bd27589b71a0b406b982485051f32b7c40c9d2c1
  2.8.0-rc6: d13db76145a9844e2a3302f561e907056f9e21a0
  2.8.0: 41fd86128995f06502954dd6d6269c22f5e389f7
  2.8.1: 1bb493318ff6c0c87334eb95640b89a16e4357d8
  2.8.2: 3be038b9d095ce3dece7918aae810d14fe770400
  2.6.17: b5423e1c423d502074cbd0b21bd4e820409d2003
  2.8.3: a751371eeed5f5f02965eb34d989c1963dd8d8c7
  2.8.4: 79b156cc9d8bff5a022fdc6d28d5c42999ddcb4f
  2.8.5: f0eb48609ff66ead3c7f06bbe8a8dd1aa7341b73
  2.8.6: 8680046580c75987961241f2e1e417c242b91a49
  2.8.7: acc369093ec74223e6da207921595187f7e64998
  2.8.8: aa811f399db58c92c8ec5e48271d307e9ab8eb81
  2.8.9: 003ccdc175816e0a751919cf508f1318e54aac1e
  2.8.10: 339ddf82e01a16ad912d1c1d59b02f3fab58d9d9
  2.8.11: 3e3a4603781514f239f040287d3ef1097eb02a76
  2.8.12: 56c86a4f9eccaf29f934433c7c67a175e404b2f6
  2.8.13: a72925a35849eb2d38a1ea076a3db82072d4ee43
  2.8.14: fd0edc045f2b53057d7f6ab38e2fe99086c87e8d
  2.8.15: afc0d753cea68a26038775df2dea75a76e3d0e1d
  2.8.16: 198045c8291dd832788ac8a17d2e565752499942
  2.8.17: 913479f9d2a283bfaadd1444e17e7bab560e5d1e
  3.0.0-rc1: f0934db86791e32053f8b21ddec5965793edff19
  2.8.18: 129629262fea2bc60daa542f52457e65e6aa7fd5
  2.8.19: 3e362f4770ac2fdbdce58a5aa951c1967e0facc8
  3.0.0: c75fd32900187a7c9f9d07c412ea3b3315691c65
  2.8.20: 45f134113fb3d75b8c37f7968e46565a70800091
  3.0.1: fe1d06599042bfe6a0e738542f302ce9533dde88
  2.8.21: 52f619d3d301fc7ae498a1d4cb4d44ecebc5b0f9
  3.0.2: a38755fe9a669896f7c5d8cd3ebbf76d59712002
  3.0.3: 0e2d7707327986ae652df717059354b358b83358
  3.0.4: cccc58b2b8643930840870f17280fcae57ed7675
  2.8.22: 78a70b32cdd3a4ccc58880d1821fb828d091bb36
  2.8.23: 828fc5d4011e6141fabb2ad6ebc193e8f0d08cfa
  3.0.5: ad3ee178c42bfcfd310c72bbddffbbe35db9b4a6
  3.0.6: 4b1c7b1201984bca8f7f9c6c58862f6928cf0a25
  3.0.7: e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c
  3.2.0: 0c1820931094369c8cc19fc1be62f598bc5961ca
  3.2.1: 26c0fc282369121b4e278523fce122910b65fbbf
