---
- name: install dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libc6-dev
  when: ansible_os_family == "Debian"

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == "RedHat"

- name: install dependencies
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == 'Suse'

- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  when: redis_travis_ci is not defined

# get_url on Ansible 1.x only supports sha256 checksumming, so we're only
# using `redis_checksums` on Ansible 2.x because they're sha1.
- name: set redis checksum
  set_fact:
    redis_checksum: "sha1:{{ redis_checksums[redis_version] }}"
  when:
    - redis_verify_checksum|bool
    - redis_checksum is not defined
    - redis_version in redis_checksums
    - ansible_version.major >= 2

- name: download redis (ansible 1.x)
  get_url:
    url: "{{ redis_download_url }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
    sha256sum: "{{ redis_checksum|default(omit) }}"
  when:
    - not redis_tarball
    - ansible_version.major < 2

- name: download redis (ansible 2.x)
  get_url:
    url: "{{ redis_download_url }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
    checksum: "{{ redis_checksum|default(omit) }}"
  when:
    - not redis_tarball
    - ansible_version.major >= 2

- name: upload redis
  copy:
    src: "{{ redis_tarball }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
  when: redis_tarball

- name: extract redis tarball
  unarchive:
    src: /usr/local/src/redis-{{ redis_version }}.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    copy: no

- name: compile redis
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: /usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: create redis install directory
  file:
    path: "{{ redis_install_dir }}"
    state: directory

- name: create /etc/redis
  file:
    path: /etc/redis
    state: directory

- name: add redis user
  user:
    name: "{{ redis_user }}"
    comment: "Redis"
    home: "{{ redis_install_dir }}"
    shell: /bin/false
    system: yes

- name: create /var/run/redis
  file:
    path: /var/run/redis
    state: directory
    owner: "{{ redis_user }}"

- name: install redis
  command: make PREFIX={{ redis_install_dir }} install
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: "{{ redis_install_dir }}/bin/redis-server"
