# file: postgresql/tasks/databases.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: PostgreSQL | Make sure the PostgreSQL databases are present
  postgresql_db:
    name: "{{item.name}}"
    encoding: "{{postgresql_encoding}}"
    lc_collate: "{{postgresql_locale}}"
    lc_ctype: "{{postgresql_locale}}"
    template: "template0"
    state: present
  with_items: postgresql_databases
  when: postgresql_databases|length > 0

- name: PostgreSQL | Add hstore to the databases with the requirement
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  shell: "psql {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS hstore;'"
  with_items: postgresql_databases
  when: item.hstore is defined and item.hstore

- name: PostgreSQL | Add uuid-ossp to the database with the requirement
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  shell: "psql {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS uuid-ossp;'"
  with_items: postgresql_databases
  when: item.uuid_ossp is defined and item.uuid_ossp
