---
services: docker

env:
  - distro: centos7
  - distro: centos6
    playbook: test-source-install.yml
  - distro: ubuntu1604
  - distro: ubuntu1404
    playbook: test-source-install.yml
  - distro: debian8
    playbook: test-source-install.yml

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
