- name: Ensure we have a deploy group
  group:
    name: deploy

- name: Ensure we have a deploy user
  user:
    name: deploy
    comment: "Deploy user"
    shell: /bin/bash
    group: deploy

## This will ensure that the listed keys are present
## but it does not remove other keys. If we have a need to revoke
## access we'll have to do something different.
- name: Create authorized_keys files for local accounts
  authorized_key:
    user: "{{ item[0] }}"
    key: https://github.com/{{ item[1] }}.keys
    comment: "{{ item[1] }}"
  with_nested:
    #- ['deploy', 'ubuntu', 'root']
    - ['deploy', 'root']
    - "{{ github_users }}"
  register: add_authorized_keys

- name: Only allow ssh access with keys
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: add_authorized_keys is success
  notify: sshd restart
