---

rvm1_temp_download_path: '/tmp'

rvm1_default_ruby_version: '{{ rvm1_rubies | last if rvm1_rubies and rvm1_rubies is iterable else rvm1_rubies }}'

rvm1_rvm: '{{ rvm1_install_path }}/bin/rvm'

rvm1_symlink_binaries:
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'
  - 'testrb'

rvm1_symlink_bundler_binaries:
  - 'bundle'
  - 'bundler'

rvm1_symlink_to: '/usr/local/bin'
