---
- name: restart redis
  service:
    name: "{{ redis_service_name }}"
    state: restarted
  when: redis_as_service

- name: restart sentinel
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
  when: redis_as_service
